sudo: required

language: go

services:
- docker

env:
  global:
  - IMAGE_NAME: rms1000watt/hello-world-travis-docker-golang

script:
- docker build -t "$IMAGE_NAME" .

before_deploy:
- datetime="$(date +'%Y%m%d%H%M')"
- version="$(cat .version)"
- git_hash="$(git log -n 1 --pretty=format:'%H')"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${datetime}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_hash}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
- docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"

deploy:
  provider: script
  script: >-
    docker push "${IMAGE_NAME}:latest" &&
    docker push "${IMAGE_NAME}:${datetime}" &&
    docker push "${IMAGE_NAME}:${git_hash}" &&
    docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
